### ISSUE TITLE
bibliography Rd examples fail if XML not installed

### ISSUE THREAD

**Issue by mwmclean** [cboettig/knitcitations#101]
The example `citet(citation("XML"))` in `bibliography.Rd` fails if `XML` has not been installed.  This is currently preventing me from submitting an update to CRAN for `RefManageR`, which now uses `xml2` instead of `XML`.

**Comment by cboettig** [comment]
@mwmclean Thanks, right, all the examples should have stuck with direct dependencies.  Fix should be headed to CRAN shortly, sorry about that.

**Comment by mwmclean** [comment]
@cboettig thanks for the quick fix.  Any reason I'm not seeing this on CRAN yet?

**Comment by cboettig** [comment]
I'm wondering that too, never got the response from CRAN on submission, I'll have to see if it didn't go through.  Never had that happen before on cran

**Comment by cboettig** [comment]
should be on cran now
