### ISSUE TITLE
Citations by DOI 

### ISSUE THREAD

**Issue by lavergnetse** [cboettig/knitcitations#109]
Hi I have been happily using knitcitations for some time. But since yesterday it does not work anymore ...
Could someone help? Thanks in advance.

> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252   
[3] LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.1 tools_4.1.1   
> library(bibtex)
> library(knitcitations)
> cleanbib()
> options("citation_format" = "pandoc")
> # These ones are from knitcitations/examples/citations.Rmd
> citet("10.1111/j.1461-0248.2005.00827.x")
Ignoring entry '2006'  (line1) because:
	A bibentry of bibtype ‘Article’ has to specify the field: c("journaltitle", "journal")
[1] "@"
> citep(c("10.1111/j.1461-0248.2005.00827.x","10.1890/11-0011.1"))
Ignoring entry '2006'  (line1) because:
	A bibentry of bibtype ‘Article’ has to specify the field: c("journaltitle", "journal")
Error in if (entry$key %in% keys) { : argument is of length zero
> citep(c(Michaels = "10.1111/j.1755-263X.2012.00241.x"))
Ignoring entry '2012'  (line1) because:
	A bibentry of bibtype ‘Article’ has to specify the field: c("journaltitle", "journal")
Error in if (entry$key %in% keys) { : argument is of length zero
> # This one is a citations I've been using before without issue 
> citet("10.1016/0304-4076(90)90080-D")
Ignoring entry '1990'  (line1) because:
	A bibentry of bibtype ‘Article’ has to specify the field: c("journaltitle", "journal")
Error in if (entry$key %in% keys) { : argument is of length zero
>

**Comment by mwmclean** [comment]
This issue will disappear if you install the development version of `RefManageR` from GitHub: `devtools::install_github("ropensci/RefManageR")`.

**Comment by lavergnetse** [comment]
Problem solved indeed. Thanks a lot.
