### ISSUE TITLE
Using numeric citations removes the final bibliography list

### ISSUE THREAD

**Issue by lmmx** [cboettig/knitcitations#70]
After setting `cite_options(cite.style="numeric")`, #26 , I get numbered citations as desired, but subsequently no final references list is produced at the end of the document. I tried changing cite.style back to default "authoryear" at the end of my document but the first setting overrides it.

Is it possible to get this?

* The superscript doesn't work properly for me either, but not producing a final bibliography is the main issue.
* I'm also wondering if it'd be possible to switch the [1;2] inline numeric citation style to (1, 2) etc., but it seems to be hardcoded? Trying (naively) to simply rewrite the apparent function fails:

<code>
citepcomma <- function (x, ...) {
    bib <- do.call(c, lapply(x, knit_cite, ...))
    citation_format <- getOption("citation_format", "text")
    if (citation_format == "pandoc")
        paste0("(", paste0("@", sapply(bib, function(b) b$key), 
            collapse = ", "), ")")
    else Citep(bib, ...)
}
</code>

`citepc(c("10.1038/nrc3690","10.1126/science.7529940"))`
`Error in match.fun(FUN) : object 'knit_cite' not found`

**Comment by cboettig** [comment]
I think this issue is resolved by `bibpunct` and the order of operations, allbeit perhaps not ideally.  So I will close for now, though PR on alternative approaches always welcome.

**Comment by sobradob** [comment]
Hi,

I am having similar issues.

```
{r}
summary(cars)
library(knitcitations)
  library(bibtex)
cite_options(cite.style="numeric")
```

This gives me numeric citations but no reference whilst putting the code below gives me a reference but no numeric citations.

```
{r}
summary(cars)
library(knitcitations)
  library(bibtex)
cite_options(citation_format = "pandoc", check.entries=FALSE, cite.style="numeric")
```

[errExample.txt](https://github.com/cboettig/knitcitations/files/83477/errExample.txt)

Its my first attempt at using the package, so I might be doing something wrong.

**Comment by cboettig** [comment]
thanks, I'll try and take a look soon
