### ISSUE TITLE
Unwanted publisher info after journal.

### ISSUE THREAD

**Issue by dhimmel** [cboettig/knitcitations#73]
I have noticed my citations include the journal's publisher info. For example,

> Kuhn M, Campillos M, Letunic I, Jensen LJ, Bork P. A side effect resource to capture phenotypic effects of drugs. Mol Syst Biol. **Wiley-Blackwell;** 2010;6. doi:10.1038/msb.2009.98

This occurs with the default style as well as the [other styles I found here](https://github.com/citation-style-language/styles) and tried (`plos.csl`, `peerj.csl`, and `biomed-central.csl`). Should I fix this by editing the `.csl` or is this a `knitcitations` issue?

**Comment by cboettig** [comment]
Given that you mention CSL I assume you're using the pandoc mode?  As long as knitcitations is generating the appropriate bibtex, than this is a CSL issue.  But if knitcitations is putting the publisher's info in, say, the journal name field of the bibtex, than it's either knitcitations or an error in the crossref metadata.

**Comment by dhimmel** [comment]
> Given that you mention CSL I assume you're using the pandoc mode?
Yes, pandoc mode.

> But if knitcitations is putting the publisher's info in, say, the journal name field of the bibtex
The bibtex file is correct.

> As long as knitcitations is generating the appropriate bibtex, than this is a CSL issue.
Thanks for helping me narrow down the issue. I will investigate the CSL files and report back with a solution.

**Comment by danlinden** [comment]
This is happening to me.  I'm using pandoc mode, the bibtex file is correct, and I am not specifying a CSL file.  I was hoping to create, write, and then read the bibtex file using `<knitcitations>` so that very little had to be included with the markdown file (for a journal article supplement).  But right now I have to manually edit the bibtex file to delete publisher information.  Not sure why publisher/editor is included with a journal article.

**Comment by cboettig** [comment]
@danlinden The fields that appear are those specified by the CSL file.  Pandoc uses it's own default CSL file if you don't supply one.

If pandoc's default CSL is not formatted the way you want, then you should provide your own CSL file that has the desired formatting, as @dhimmel did.

**Comment by dhimmel** [comment]
I'm confused why publisher information is included by the default style, since it's undesirable. Additionally, why is it included in the PLOS and PeerJ templates, since these journals do not include publisher information in their actual references?

**Comment by cboettig** [comment]
I'm afraid those questions would be better directed at the maintainers of those CSL files, or to the maintainer of pandoc regarding it's choice of default. This is really out of scope for knitcitations since it's handled by those other parts already.
