### ISSUE TITLE
Server error for doi

### ISSUE THREAD

**Issue by bjcochrane** [cboettig/knitcitations#84]
I have tried several doi entries  such as `r citet("10.1038/nature09298")`, which have worked fine previously; the response  I receive is

server error for doi "http://dx.doi.org/10.1038/nature09298", you may want to try again.
no results with relavency score greater than 'min.relevance' successfully retrieved.

Note that this was preceded by the following in my .Rmd file:

```{r}
library(knitcitations)
cleanbib()
cite_options(citation_format = "pandoc", style = "text",
  hyperlink = FALSE, cite.style = "authoryear", super = FALSE,
  max.names = 4)
```

Suggestions are most welcome!

**Comment by cboettig** [comment]
@bjcochrane Thanks for the bug report.  I think the crossref servers occasionally get overloaded.  At the moment I cannot reproduce this error.  Can you try it again a few times?  I'm pretty sure the error should be independent of the `cite_options` you set.
