### ISSUE TITLE
Error in modifying igraph package

### ISSUE THREAD

**Issue by proj786** [cboettig/knitcitations#91]
I am trying to add a function in igraph package. I created a simple c mycheck program in igraph/src directory and corressponding R funtion which called the mycheck program  in igraph/R directory.

**mycheck.c file**
#include "igraph_community.h"
#include "igraph_memory.h"
#include "igraph_interface.h"
#include "igraph_iterators.h"
#include "config.h"

void mycheck()
{
 printf("Hello, this is me");
}

**mycheck.r file**
mycheck1 <- function() {
.Call("mycheck")
}

then, I executed following two commands:
1) R CMD build igraph
2)R CMD INSTALL igraph_1.0.1.tar.gz -l .

first command was successful but 2nd gave the following error:
Error in .install_package_code_files(".", instdir) : 
files in '/tmp/RtmpYfHcPe/R.INSTALL62f72c3bd433/igraph/R' missing from 'Collate' field:
  mycheck.r
ERROR: unable to collate and parse R files for package ‘igraph’

**Comment by cboettig** [comment]
This looks like an `igraph` issue having nothing to do with knitcitations, so please post in there, I'm closing this issue.  (Though from the error message it looks like you haven't updated the collate list in the DESCRIPTION file to include the file you added in `R/`)
